name: scalpel-exceptt
version: 0.1.0.0
synopsis: demonstrate how to yield error messages from scraper
description: using monad transformer ExceptT with ScraperT
author: Benjamin Weber <one@bwe.im>
maintainer: Benjamin Weber <one@bwe.im>
github: benjaminweb/scalpel-exceptt
category: Other

default-extensions:
  - OverloadedStrings

dependencies:
  - base
  - scalpel
  - mtl
  - text

library:
  source-dirs: src

executable:
  source-dirs: app
  main: Main.hs
